import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;






/**
 *
 * @author hadielmekawi
 */




public class GuessWord2 extends javax.swing.JFrame {
    
    
 String FindWord = "";
        
        
    /**
     * Creates new form GuessWord2
     */
        
    public GuessWord2() throws FileNotFoundException, IOException {
        initComponents();
        //String Words[]={"hello","20Chix","revolu","inside","computer","screen"};
        BufferedReader in = new BufferedReader(new FileReader("/Users/hadielmekawi/Desktop/Word.txt"));
        String str;
        ArrayList<String> lines = new ArrayList<String>();
        while((str = in.readLine()) != null){
            lines.add(str);
        }
        String[] linesArray = lines.toArray(new String[lines.size()]);
        Random ran = new Random();
        
        int ForRan= ran.nextInt(1);
        //int ForRan2 = ran.nextInt(6);
       // System.out.println("random num "+ForRan2);
       FindWord = linesArray[ForRan];
        // FindWord= Words[ForRan2];

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyMessage = new javax.swing.JLabel();
        tryLetter = new javax.swing.JButton();
        HangManDisplay = new javax.swing.JButton();
        Char0 = new javax.swing.JLabel();
        Char1 = new javax.swing.JLabel();
        Char2 = new javax.swing.JLabel();
        Char3 = new javax.swing.JLabel();
        Char4 = new javax.swing.JLabel();
        inCorrect = new javax.swing.JLabel();
        aLetter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        GameOver = new javax.swing.JLabel();
        YouWin = new javax.swing.JLabel();
        Char6 = new javax.swing.JLabel();
        Char5 = new javax.swing.JLabel();
        Char7 = new javax.swing.JLabel();
        Char8 = new javax.swing.JLabel();
        Char9 = new javax.swing.JLabel();
        WeWin = new javax.swing.JLabel();
        DisplayWord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MyMessage.setBackground(new java.awt.Color(255, 255, 0));
        MyMessage.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        MyMessage.setText("look here");

        tryLetter.setText("Try Letter");
        tryLetter.setActionCommand("");
        tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryLetterActionPerformed(evt);
            }
        });

        HangManDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangManDisplayActionPerformed(evt);
            }
        });

        Char0.setText("X");

        Char1.setText("X");

        Char2.setText("X");

        Char3.setText("X");

        Char4.setText("X");

        inCorrect.setText("0");

        aLetter.setText("e");
        aLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLetterActionPerformed(evt);
            }
        });

        jLabel1.setText("Errors:");

        GameOver.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N

        YouWin.setText("0");

        Char6.setText("X");

        Char5.setText("X");

        Char7.setText("X");

        Char8.setText("X");

        Char9.setText("X");

        WeWin.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tryLetter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WeWin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DisplayWord, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(Char5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Char6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Char8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Char9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Char0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Char1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Char2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Char3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Char4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Char7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MyMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(HangManDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Char0)
                            .addComponent(Char1)
                            .addComponent(Char2)
                            .addComponent(Char3)
                            .addComponent(Char4)
                            .addComponent(Char6)
                            .addComponent(Char5)
                            .addComponent(Char7)
                            .addComponent(Char8)
                            .addComponent(Char9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WeWin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DisplayWord, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inCorrect))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(tryLetter)
                .addGap(18, 18, 18)
                .addComponent(MyMessage)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HangManDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int charPos; 
    private void tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryLetterActionPerformed
        // TODO add your handling code here:
  
          
          
        String letter = aLetter.getText();
        String Winning ="You Win.Click OK to try again.";
        String Lost="I'm Sorry but you lost.Click OK to try again.";
        String MessageBox="Message";
        
        Char0.setVisible(false);
        Char1.setVisible(false);
        Char2.setVisible(false);
        Char3.setVisible(false);
        Char4.setVisible(false);
        Char5.setVisible(false);
        Char6.setVisible(false);
        Char7.setVisible(false);
        Char8.setVisible(false);
        Char9.setVisible(false);
        
        String C0=Char0.getText();
        String C1=Char1.getText();
        String C2=Char2.getText();
        String C3=Char3.getText();
        String C4=Char4.getText();
        String C5=Char5.getText();
        String C6=Char6.getText();
        String C7=Char7.getText();
        String C8=Char8.getText();
        String C9=Char9.getText();
        int lenghtword = FindWord.length();
        System.out.println("lenghtword"+lenghtword );
     
     
       
        if(lenghtword ==3){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        }
        
        if(lenghtword ==4){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        }
        
        if(lenghtword ==5){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        }
        
        if(lenghtword ==6){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        Char5.setVisible(true);
        }
        
        if(lenghtword ==7){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        Char5.setVisible(true);
        Char6.setVisible(true);
        }
        
        if(lenghtword ==8){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        Char5.setVisible(true);
        Char6.setVisible(true);
        Char7.setVisible(true);
        }
        
        if(lenghtword ==9){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        Char5.setVisible(true);
        Char6.setVisible(true);
        Char7.setVisible(true);
        Char8.setVisible(true);
        }
        
        if(lenghtword ==10){
        Char0.setVisible(true);
        Char1.setVisible(true);
        Char2.setVisible(true);
        Char3.setVisible(true);
        Char4.setVisible(true);
        Char5.setVisible(true);
        Char6.setVisible(true);
        Char7.setVisible(true);
        Char8.setVisible(true);
        Char9.setVisible(true);
        }
        int incorrectG = Integer.parseInt(inCorrect.getText());
        int win = Integer.parseInt(YouWin.getText());//for winning
        charPos =FindWord.indexOf(letter, charPos);
        MyMessage.setText("position is"+ charPos);
        DisplayWord.setText(FindWord);
      

        if (charPos == 0) {Char0.setText(letter);win++;if(C0.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 1) {Char1.setText(letter);win++;if(C1.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 2) {Char2.setText(letter);win++;if(C2.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 3) {Char3.setText(letter);win++;if(C3.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 4) {Char4.setText(letter);win++;if(C4.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 5) {Char5.setText(letter);win++;if(C5.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 6) {Char6.setText(letter);win++;if(C6.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 7) {Char7.setText(letter);win++;if(C7.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 8) {Char8.setText(letter);win++;if(C8.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 9) {Char9.setText(letter);win++;if(C9.equals(letter))win--;System.out.println(""+win);}
        if (charPos == -1){incorrectG = incorrectG + 1;
        if(incorrectG ==13){   
        JOptionPane.showMessageDialog(null, Lost, "InfoBox: " + MessageBox, JOptionPane.INFORMATION_MESSAGE);
        incorrectG =0;
        HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/Loading.png"));
        Char0.setText("X");
        Char1.setText("X");
        Char2.setText("X");
        Char3.setText("X");
        Char4.setText("X");
        Char5.setText("X");
        Char6.setText("X");
        Char7.setText("X");
        Char8.setText("X");
        Char9.setText("X");         
        }//nestead if statment game over
        }//for char = -1   
       charPos =FindWord.indexOf(letter, charPos+1);
        MyMessage.setText("position is"+ charPos);
        if (charPos == 0) {Char0.setText(letter);win++;if(C0.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 1) {Char1.setText(letter);win++;if(C1.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 2) {Char2.setText(letter);win++;if(C2.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 3) {Char3.setText(letter);win++;if(C3.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 4) {Char4.setText(letter);win++;if(C4.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 5) {Char5.setText(letter);win++;if(C5.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 6) {Char6.setText(letter);win++;if(C6.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 7) {Char7.setText(letter);win++;if(C7.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 8) {Char8.setText(letter);win++;if(C8.equals(letter))win--;System.out.println(""+win);}
        if (charPos == 9) {Char9.setText(letter);win++;if(C9.equals(letter))win--;System.out.println(""+win);}
        if (win == lenghtword){
        JOptionPane.showMessageDialog(null, Winning, "InfoBox: " + MessageBox, JOptionPane.INFORMATION_MESSAGE);
        int input = JOptionPane.showOptionDialog(null, "Do you want to play again?", "The title", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        if(input == JOptionPane.OK_OPTION){    
        try {
        GuessWord2 hd = new GuessWord2();
        } catch (IOException ex) {
        Logger.getLogger(GuessWord2.class.getName()).log(Level.SEVERE, null, ex);
        }
        }//finish option OK
        win = 0;
        incorrectG =0;
        HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/Loading.png"));
        Char0.setText("X");
        Char1.setText("X");
        Char2.setText("X");
        Char3.setText("X");
        Char4.setText("X");
        Char5.setText("X");
        Char6.setText("X");
        Char7.setText("X");
        Char8.setText("X");
        Char9.setText("X");
 }
      
        String ss = Integer.toString(incorrectG);
        inCorrect.setText(ss);
        
        String ss1 = Integer.toString(win);
        YouWin.setText(ss1);     
        HangManDisplayActionPerformed(evt);//click image botton
      
       
       
      

    }//GEN-LAST:event_tryLetterActionPerformed

    
    private void HangManDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangManDisplayActionPerformed

        
        
    
          
        int display = Integer.parseInt(inCorrect.getText());
        inCorrect.setText(Integer.toString(display));
 
        
        
        if (display == 1) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/1.png"));
        }
        if (display == 2) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/2.png"));
        }
        if (display == 3) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/3.png"));
        }
        if (display == 4) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/4.png"));
        }
        if (display == 5) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/5.png"));
        }
        if (display == 6) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/6.png"));
        }
        if (display == 7) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/7.png"));
        }
        if (display == 8) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/8.png"));
        }
        if (display == 9) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/9.png"));
        }
        if (display == 10) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/10.png"));
        }
        if (display == 11) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/11.png"));
        }
        if (display == 12) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/12.png"));
        }
        
        if (display == 13) {
            HangManDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Hang man/13.png"));
        }
        
        
        
        //  HangManDisplayActionPerformed(evt);
    }//GEN-LAST:event_HangManDisplayActionPerformed

    private void aLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aLetterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessWord2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessWord2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessWord2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessWord2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuessWord2().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuessWord2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Char0;
    private javax.swing.JLabel Char1;
    private javax.swing.JLabel Char2;
    private javax.swing.JLabel Char3;
    private javax.swing.JLabel Char4;
    private javax.swing.JLabel Char5;
    private javax.swing.JLabel Char6;
    private javax.swing.JLabel Char7;
    private javax.swing.JLabel Char8;
    private javax.swing.JLabel Char9;
    private javax.swing.JLabel DisplayWord;
    private javax.swing.JLabel GameOver;
    private javax.swing.JButton HangManDisplay;
    private javax.swing.JLabel MyMessage;
    private javax.swing.JLabel WeWin;
    private javax.swing.JLabel YouWin;
    private javax.swing.JTextField aLetter;
    private javax.swing.JLabel inCorrect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tryLetter;
    // End of variables declaration//GEN-END:variables
}
